### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by njustesen** [njustesen/botbowl#171]
This is the new politically correct standard that we should follow.

We should consider carefully if it can create some issues with our PRs or if GitHub manages that automatically.

**Comment by njustesen** [comment]
Should we make short term milestone where we wrap up the all the current non-stale PRs and then we do the renaming?

**Comment by mrbermell** [comment]
Yes, sounds good! And yes, let's not wait for the cython pathfinding, that one will take some more time and thorough thought!
