### ISSUE TITLE
Out of the box RL friendly gym env

### ISSUE THREAD

**Issue by mrbermell** [njustesen/botbowl#185]
There should be a gym environment that is intended for use with out of the box RL code from github and scientific papers. The current gym environment FFAI has requires a lot of adaptation (see a2c_example.py). 

By making an ffai gym env that is more integration friendly it becomes easier to benchmark state of the art algorithms for blood bowl and makes it easier to get started with the framework. 

Exactly how this could be done can be discussed, here are the two main issues: 

-  **Only spatial observations**. Move non-spatial observations into layers. This will create a huge spatial observation matrix, so maybe we need to question many of the none spatial observation. 
- **Actions as int**. This is the standard way of handling discrete action spaces and is already implemented in a2c_example.py 

The action mask needs to be handled somehow too, I think it's reasonable to have a separate getter-function for it instead of clogging down what is returned by gym.step() but I'm not sure...

**Comment by njustesen** [comment]
I think you'll lose a lot by removing the non-spatial data stream. We are currently doing what DeepMind does in StarCraft and I believe OpenAI does for Dota, having a non-spatial and spatial input stream. The problem is that RL code from github and scientific papers are focused on small and simple environments so they cannot handle dual input streams - but they should!

**Comment by mrbermell** [comment]
Yes, I know and I agree, they should! I'm not suggesting we scrap the idea of a non spatial input, just extend the framework. I think it's also worthwhile to have the ability to test that hypothesis: that non spatial input is needed. 

And to clarify, I'm not saying remove non spatial observations, I'm say add that information to spatial layers instead so the observation becomes a single tensor. Though it's an inefficient representation (to say the least!), it saves a lot of coding time. I don't want to know how many hours I poured into getting SEED RL work with multiple observation tensors...

**Comment by njustesen** [comment]
I would suggest trying this out in a quick hacky way and if the results are good, then we can consider to building it into the gym env.
