### ISSUE TITLE
Improve documentation on how to build with cython when there's no c++ compiler

### ISSUE THREAD

**Issue by njustesen** [njustesen/botbowl#188]
It's currently not straightforward to figure out how to fix:
```
You've built botbowl without cython compilation. Check docs/installation.md for details.
```
after running ```pip install .``` without a c++ compiler.

The docs/installation.md should provide some details instead of a link to the cython documentation.

**Comment by mrbermell** [comment]
I think we can closed this issue since #189 is merged to master now. @njustesen  agree?

**Comment by njustesen** [comment]
It's not merged yet. Should it? :)

**Comment by mrbermell** [comment]
Haha, I just noticed. Sorry about the spamming. Yes we should :)
