### ISSUE TITLE
Possible Bug 'improved-env' branch

### ISSUE THREAD

**Issue by AurelianTactics** [njustesen/botbowl#210]
Sorry if I'm misreading this and wasting your time but should this line use the self.away_reward_func():

https://github.com/njustesen/botbowl/blob/improved-env/botbowl/ai/env.py#L543

**Comment by njustesen** [comment]
I am pretty sure it should. @mrbermell ?

**Comment by mrbermell** [comment]
Thanks for spotting it. You are correct. I've made the update in the PR. 

You are more than welcome to comment in the PR itself, I think it's easier to track the conversations that way :) 

And don't worry about wasting anyone's time. I'm super happy to help, answer questions etc if I can. And in no time, it'll be you helping me! :100:

**Comment by njustesen** [comment]
What's the purpose with `away_reward_func`? Looks like it's never used.

**Comment by mrbermell** [comment]
> What's the purpose with `away_reward_func`? Looks like it's never used.

It's only used if you're playing on both sides i.e. both home and away agents have agent.human=True. In that case it's needed if your reward is based in Game.state.reports. 

But we don't do that in the examples. So it's never used.
