### ISSUE TITLE
pathfinding does not terminate at ball pickup

### ISSUE THREAD

**Issue by mrbermell** [njustesen/botbowl#211]
During a MoveAction, I think you should only pickup the ball if you select the square with the ball in.  i.e. the pathfinding should stop expanding its search if it picks up the ball. It currently doesn't and below test fails: 

```python 
@pytest.mark.parametrize("pf", pathfinding_modules_to_test)
def test_forced_pickup_path(pf):
    game, (player1, player2, player3) = get_custom_game_turn(player_positions=[(1, 1), (1, 2), (2, 2)],
                                                             ball_position=(2, 1),
                                                             pathfinding_enabled=True)
    paths = pf.get_all_paths(game, player1)
    assert len(paths) == 1
    assert paths[0].get_last_step() == game.get_ball_position()
```

If you agree, I'll make a PR with a solution. 

The reason this bug doesn't show more frequently is because the pickup probability in included in the path probability. So the pathfinding will prefer paths that doesn't pickup the ball. That's why the test has to force the pickup by blocking all other adjacent squares. 

PS.
Again, the determinstic tree searcher assumed that paths terminate at the ball. And somehow got in a situation where it discovered this bug :1st_place_medal:

**Comment by njustesen** [comment]
No strong opinion here but what if the only path to a square is through the ball?

**Comment by njustesen** [comment]
I think the argument that RL agents don't look at intermediate paths is very good. Let's do it.

**Comment by mrbermell** [comment]
Issue solved and merged to master
