### ISSUE TITLE
Sometimes the active player can't block during a blitz move

### ISSUE THREAD

**Issue by njustesen** [njustesen/botbowl#215]
This happens sometimes but I can't see a pattern.
<img width="357" alt="Screenshot 2022-03-14 at 23 29 50" src="https://user-images.githubusercontent.com/1433421/158271840-826d43e5-a01c-4754-9a64-31675f3e5c6b.png">

A clue is the has_blocked might not always be reset.
<img width="329" alt="Screenshot 2022-03-14 at 23 30 50" src="https://user-images.githubusercontent.com/1433421/158271900-edacee7c-f088-48d7-aec5-cce04b1ffcce.png">

**Comment by mrbermell** [comment]
Solved now if I'm not mistaken?

**Comment by njustesen** [comment]
Yeah, at least I solved one reason why this would happen. So let's close it for now.
