### ISSUE TITLE
Getting some values above 1.0 in the non-spatial observations

### ISSUE THREAD

**Issue by AurelianTactics** [njustesen/botbowl#232]
When doing 1 vs. 1 games I'm getting some values of 1.125 in what I think is this index of the non-spatial observations: https://github.com/njustesen/botbowl/blob/main/botbowl/ai/env.py#L275 . It's usually index 19 of the non-spatial obs (4 times) but it has happened once in index 28. Always value of 1.125.

It happens infrequently. Sometimes millions of steps go by without it occurring. It might be an issue with something on my end with a gym wrapper. I've only had it happen on 1 vs 1 games and not 11 vs 11 games. I thought it might be due to one of the recent fixes in the env.py file (https://github.com/njustesen/botbowl/commit/34a3ca084e8d88d68909c6bf11a9b37f11d85006) but I'm not sure why that would change the number of rerolls.

I'll see if I can narrow it down and try some seeds to make it reproducible.

**Comment by njustesen** [comment]
It should be these two:
Index 19: ```non_spatial_obs[next(index)] = active_team.state.rerolls / 8.0```
Index 28: ```non_spatial_obs[next(index)] = opp_team.state.turn / 8.0```

```non_spatial_obs[19] > 1```  can happen in smaller variants if there are many kickoffs with brilliant coaching or cheering fans. Not sure how ```non_spatial_obs[28] > 1``` can happen.

We could clamp the final vector as it wouldn't really make a difference.

**Comment by AurelianTactics** [comment]
Ah, thanks for the explanation. I ran like 50000 games of 11 vs 11 the past couple of days and it didn't occur. I'm going to close this issue then. I'll add some code in my wrapper to clamp at 1 or maybe just let the observation space let values > 1 occur for non-spatial.
