### ISSUE TITLE
Saving a game doesn't work

### ISSUE THREAD

**Issue by danj3000** [njustesen/botbowl#87]
Error message is displayed.

**Comment by danj3000** [comment]
The immediate problem with file references is easily fixed, but then the game will disqualify the team on reload.

Removing the clocks at save prevents this, but then how to re-establish the clocks on restart ??

**Comment by njustesen** [comment]
Should probably be connected to a user management system. I.e. users has saved games.

**Comment by njustesen** [comment]
Niels will do a fix without forward model first.
